### PR TITLE
Use `useLayoutEffect` instead of `useEffect` for string parsing and height measurements

### LINKED ISSUE #166: Move height to layout effect
https://github.com/Expensify/react-native-live-markdown/blob/348fcd2034d4599738f8a364777348f7b2e8ce82/src/MarkdownTextInput.web.tsx#L467-L474

Hey! Reviewing the web code, and I'm wondering if this should get moved to a layout effect since it's adjusting the height and you'd want to do this before painting. I'm happy to PR it if so!

### PR DESCRIPTION
**Pull request by nandorojo**
### Details

> useLayoutEffect is a version of [useEffect](https://react.dev/reference/react/useEffect) that fires before the browser repaints the screen.

Screenshot 2024-02-08 at 10 34 58 AM

It's ideal for cases where dimensions are derived from a DOM element and then updates some other element before react paints the screen. These seem like good use cases.

### Related Issues

GH_LINK

close #166

### Manual Tests

I didn't add any tests, I'll try a video comparison maybe?

### CODE REVIEW

**Comment by nandorojo** [comment]
CLA throws a 404

**Comment by AndrewGable** [comment]
Oops - CLA should is added now!

**Review by tomekzaw — APPROVED** [review]

**Comment by nandorojo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tomekzaw** [comment]
Thanks!

**Pull request merged**
