### PR TITLE
fix: revert the functionality to restore cursor in value update hook

### PR DESCRIPTION
**Pull request by dominictb**
### Details

- revert the use of contentSelection to restore cursor pos during text update to cursor jumping around funny since contentSelection ref value can get outdated.
- create func to restore cursor in the ref object

### Related Issues

RCA: https://github.com/Expensify/App/issues/43312#issuecomment-2156740534
Solution: https://github.com/Expensify/App/issues/41137#issuecomment-2156739474

### CODE REVIEW

**Review by Skalakid — COMMENTED** [review]
@dominictb I see this PR introduces some custom API functions on the web implementation. The idea behind the Live Markdown Input is to make its interface nearly identical to the native `TextInput` component so people can just replace it. Adding custom API need deeper investigation and planning. If we decide to make something new it would be great to add it on iOS and Android too.
Thank you for your changes, however I think we should try solving the issue with a bit different logic. Have you tried using the currently available features of Live Markdown to fix it on the E/App side? If yes, I think you can try fixing this issue by just changing `handlePaste` event logic in `MarkdownTextInput.web.tsx`

**Comment by BartoszGrajdek** [comment]
Alright so here's what we're going to do now: We'll revert [this PR](https://github.com/Expensify/react-native-live-markdown/pull/357) since [a fix](https://github.com/Expensify/react-native-live-markdown/pull/370) for the [regression](https://github.com/Expensify/App/issues/41137#issuecomment-2153464605) I've mentioned was reverted [here](https://github.com/Expensify/react-native-live-markdown/pull/377). You'll have to make 1 PR with all of these changes and we will do our best to help you along the way with the implementation since it looks like this is a tricky bug. Our goal is to keep `react-native-live-markdown` lib as bug-free as we can and that way we can properly test it to ensure nothing breaks. 🙌🏻

**Review by Skalakid — APPROVED** [review]
LGTM, thanks for investigation. We will close @BartoszGrajdek's [PR](https://github.com/Expensify/react-native-live-markdown/pull/380) with the revert

**Review by BartoszGrajdek — APPROVED** [review]
We're basically restoring how it worked before except for `setBaseAndExtent` so it looks solid to me. I also like the idea of handling the bug in E/App itself

**Pull request merged**
