### PR TITLE
Fix cursor positioning on android on markdown style change

### PR DESCRIPTION
**Pull request by Skalakid**
### Related Issues

https://github.com/Expensify/App/issues/40504

### Manual Tests

1. Modify the MarkdownTextInput component in App. tsx with the following code:
```js
     <MarkdownTextInput
        multiline
        autoCapitalize="none"
        value={value}
        onChangeText={(val) => {
          if (val.includes(':+1:'))r {
            setMarkdownStyle({emoji: {fontSize: 30}});
          }
          setValue(val.replaceAll(':+1:', '👍'));
        }}
        style={styles.input}
        ref={ref}
        markdownStyle={markdownStyle}
        placeholder="Type here..."
        onSelectionChange={(e) => setSelection(e.nativeEvent.selection)}
        selection={selection}
      />
```
2. Clear the whole text
3. Enter :+1:
4. Check if the cursor is positioned correctly (after the emoji)

### CODE REVIEW

**Comment by robertKozik** [comment]
@Skalakid  Is it testable in example app?

**Comment by BartoszGrajdek** [comment]
> @Skalakid Is it testable in example app?

Bump 👀 

Please add some test steps 🙏🏻

**Review by robertKozik — APPROVED** [review]
I've tested on E/App - working like a charm. I didn't find any regressions in example app as well. Changes are quite straightforward so I'll approve it now.

**Comment by Skalakid** [comment]
@BartoszGrajdek @robertKozik sorry, I forgot to add test steps. The issue is present in E/App because we are changing text and styles (for example changing :+1: into an emoji). The issue is reproducible in our example app only after app modifying App.tsx file. For example like:

```js
      <MarkdownTextInput
        multiline
        autoCapitalize="none"
        value={value}
        onChangeText={(val) => {
          if (val.includes(':+1:'))r {
            setMarkdownStyle({emoji: {fontSize: 30}});
          }
          setValue(val.replaceAll(':+1:', '👍'));
        }}
        style={styles.input}
        ref={ref}
        markdownStyle={markdownStyle}
        placeholder="Type here..."
        onSelectionChange={(e) => setSelection(e.nativeEvent.selection)}
        selection={selection}
      />
```

**Pull request merged**
