### PR TITLE
Add unit test for video parse

### PR DESCRIPTION
**Pull request by nkdengineer**
### Related Issues

follow up PR: https://github.com/Expensify/react-native-live-markdown/pull/440

### CODE REVIEW

**Comment by nkdengineer** [comment]
I'll update today

**Comment by nkdengineer** [comment]
Still investigating to find the reason the test failed.

**Comment by tomekzaw** [comment]
@nkdengineer The test with ````test```` is failing because video alt text is escaped. Please come up with the fix for this input.

**Comment by nkdengineer** [comment]
@tomekzaw Actually the video tag has the format `<video>{videoName}</video>` and then the other markdowns are applied in videoName. We need some changes in `expensify-common` to prevent other markdowns from being applied inside the `video` tag.

**Comment by nkdengineer** [comment]
@tomekzaw I just added a patch about the required change in `expensify-common` let me know your thought.

**Comment by tomekzaw** [comment]
@nkdengineer Please re-build parser as the CI is failing.

**Comment by nkdengineer** [comment]
@tomekzaw Maybe I built the parser with the `expensify-common` applied patch and then the lint check failed. Do you think we need a PR in `expensify-common`?

**Comment by tomekzaw** [comment]
Yes, please propagate all necessary changes to expensify-common.

Also, can you please run `cd parser && yarn build` and commit `react-native-live-markdown-parser.js` again?

**Comment by nkdengineer** [comment]
> Yes, please propagate all necessary changes to expensify-common.

My newest commit already runs build and đupate react-native-live-markdown-parser.js. The test fails maybe as I mentioned above. I think we can hold until I create a PR in `expensify-common` and it's merged.

> Also, can you please run cd parser && yarn build and commit react-native-live-markdown-parser.js again?

**Comment by tomekzaw** [comment]
The test fails because `react-native-live-markdown-parser.js` generated on CI is different than the one that is committed.

Looks like you've added a patch in `parser/` directory – but the patch file is not listed in `package.json`.

Also, we don't run `yarn patch-package` when installing dependencies on the CI.

That's why the CI is failing.

I think we can hold this PR until the PR to expensify-common is merged.

**Comment by nkdengineer** [comment]
@tomekzaw @ZhenjaHorbach An `expensify-common` PR here.

https://github.com/Expensify/expensify-common/pull/769

**Comment by nkdengineer** [comment]
@tomekzaw The `epxensify-common` PR is merged and I bumped the version.

**Review by tomekzaw — APPROVED** [review]

**Comment by tomekzaw** [comment]
@nkdengineer Thanks for the PR!

**Pull request merged**
