### PR TITLE
Fix blockquote line height on iOS

### PR DESCRIPTION
**Pull request by tomekzaw**
### Details
This PR fixes line height inside blockquote on iOS.

When `lineHeight` style is set on `MarkdownTextInput`, React Native adds `NSParagraphStyle` with `minimumLineHeight` and `maximumLineHeight` to the attributed string.

In Live Markdown, blockquote indent is set using another `NSParagraphStyle` with `firstLineHeadIndent` and `headIndent`.

Currently, we create `NSParagraphStyle` using `[NSParagraphStyle new]`, ignoring the `NSParagraphStyle` created by React Native.

This PR uses the `NSParagraphStyle` set by React Native when creating `NSParagraphStyle` for blockquotes.

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><video src="https://github.com/user-attachments/assets/e3dc8e3b-91c4-4fda-82dc-c540f346e2f0" /></td>
<td><video src="https://github.com/user-attachments/assets/67724dd0-9fd0-4495-9488-4b7619bbd235" /></td>
</tr>
</tbody>
</table>

### Related Issues

GH_LINK

### Manual Tests
When testing, please set `lineHeight: 30` inside `styles.input` in `App.tsx`.

### CODE REVIEW

**Review by j-piasecki — DISMISSED** [review]

**Comment by tomekzaw** [comment]
Waiting for @289Adam289's review

**Comment by 289Adam289** [comment]
BUG example app iOS:

Toggle text font size button does not actually change size.

https://github.com/user-attachments/assets/fa6ee113-5e9d-41b3-9a91-900c029c112e

**Comment by tomekzaw** [comment]
@289Adam289 As for https://github.com/Expensify/react-native-live-markdown/pull/587#issuecomment-2545794089, this is not a regression since it also happens on current `main` (8b1789a): 

https://github.com/user-attachments/assets/0a9bdc2d-3e58-43ef-9b5e-bc85220492fb

**Comment by tomekzaw** [comment]
@289Adam289 I've narrowed down the root cause of this issue to those lines:

https://github.com/Expensify/react-native-live-markdown/blob/f165434a62852973f1e46b6271a49c8928d73cbe/apple/RCTTextInputComponentView%2BMarkdown.mm#L56-L63

**Review by j-piasecki — DISMISSED** [review]

**Comment by 289Adam289** [comment]
I've checked https://github.com/Expensify/react-native-live-markdown/pull/587#issuecomment-2545794089 on main and indeed it is not a regression. I will test this pr on E/App and if everything goes well I think we can merge it.

**Comment by 289Adam289** [comment]
I've tested this pr on E/App and I could not find any regressions. We can safely merge.

**Comment by tomekzaw** [comment]
Fixed baseline offset jumps when adding heading in fc1d1e9
Screenshot 2024-12-21 at 16 11 43

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><video src="https://github.com/user-attachments/assets/21105137-2ad2-4ba9-b13f-cf8ebed8b19d" /></td>
<td><video src="https://github.com/user-attachments/assets/b11c97f6-8aea-4796-a504-ea8392673c14" /></td>
</tr>
</tbody>
</table>

**Review by j-piasecki — APPROVED** [review]
🫣

**Comment by tomekzaw** [comment]
Some video recordings from E/App with visible improvements:

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td><video src="https://github.com/user-attachments/assets/efb3fb33-c7a1-4ae1-8b1c-3a9be5ef0b57" /></td>
<td><video src="https://github.com/user-attachments/assets/ae3839a8-420f-44e0-b51a-906e3ee51768" /></td>
</tr>
</tbody>
</table>

**Pull request merged**
