### PR TITLE
Bump React Native to 0.73

### LINKED ISSUE #81: Bump example app to React Native 0.73

### PR DESCRIPTION
**Pull request by robertKozik**
fixes #81

### CODE REVIEW

**Comment by benjaminkomen** [comment]
Also fixes https://github.com/Expensify/react-native-live-markdown/issues/95

**Comment by tomekzaw** [comment]
@benjaminkomen Not really, the objective of #95 is to migrate the library code in `android/src/main/java` directory (e.g. [MarkdownUtils.java](https://github.com/Expensify/react-native-live-markdown/blob/main/android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java)).

**Comment by benjaminkomen** [comment]
> @benjaminkomen Not really, the objective of #95 is to migrate the library code in `android/src/main/java` directory (e.g. [MarkdownUtils.java](https://github.com/Expensify/react-native-live-markdown/blob/main/android/src/main/java/com/expensify/livemarkdown/MarkdownUtils.java)).

Ah ok, I didn't look careful enough, I though this PR migrated all the Java code to Kotlin, but it only did what was necessary for the react native upgrade.

**Review by tomekzaw — APPROVED** [review]
Tested on Android, iOS and web

**Pull request merged**
