### PR TITLE
Add parse to text and ranges for video

### PR DESCRIPTION
**Pull request by nkdengineer**
### Details

Add parse to text and ranges for video

### Related Issues

https://github.com/Expensify/App/issues/46114

### CODE REVIEW

**Review by tomekzaw — APPROVED** [review]
Thanks for the PR! Tested on iOS, works well.

Screenshot 2024-07-26 at 10 15 24

**Comment by tomekzaw** [comment]
@ZhenjaHorbach Do you want to proceed with the review or can I merge the PR right now?

**Comment by tomekzaw** [comment]
@ZhenjaHorbach Great, thanks, merged!

**Comment by tomekzaw** [comment]
@nkdengineer I've noticed that the PR doesn't contain unit tests, can you please add the following to `parser/__tests__/index.test.ts`?

<details>

```tsx
describe('inline video', () => {
  test('with alt text', () => {
    expect('![test](https://example.com/video.mp4)').toBeParsedAs([
      {type: 'syntax', start: 0, length: 1},
      {type: 'syntax', start: 1, length: 1},
      {type: 'syntax', start: 6, length: 1},
      {type: 'syntax', start: 7, length: 1},
      {type: 'link', start: 8, length: 29},
      {type: 'syntax', start: 37, length: 1},
    ]);
  });

  test('without alt text', () => {
    expect('![](https://example.com/video.mp4)').toBeParsedAs([
      {type: 'syntax', start: 0, length: 1},
      {type: 'syntax', start: 1, length: 1},
      {type: 'syntax', start: 2, length: 1},
      {type: 'syntax', start: 3, length: 1},
      {type: 'link', start: 4, length: 29},
      {type: 'syntax', start: 33, length: 1},
    ]);
  });

  test('with same alt text as src', () => {
    expect('![https://example.com/video.mp4](https://example.com/video.mp4)').toBeParsedAs([
      {type: 'syntax', start: 0, length: 1},
      {type: 'syntax', start: 1, length: 1},
      {type: 'syntax', start: 31, length: 1},
      {type: 'syntax', start: 32, length: 1},
      {type: 'link', start: 33, length: 29},
      {type: 'syntax', start: 62, length: 1},
    ]);
  });

  test('with alt text containing markdown', () => {
    expect('![# fake-heading *bold* _italic_ ~strike~ [:-)]](https://example.com/video.mp4)').toBeParsedAs([
      {type: 'syntax', start: 0, length: 1},
      {type: 'syntax', start: 1, length: 1},
      {type: 'syntax', start: 47, length: 1},
      {type: 'syntax', start: 48, length: 1},
      {type: 'link', start: 49, length: 29},
      {type: 'syntax', start: 78, length: 1},
    ]);
  });

  test('trying to pass additional attributes', () => {
    expect('![test](https://example.com/video.mp4 "title" class="video")').toBeParsedAs([{type: 'link', start: 8, length: 29}]);
  });

  test('trying to inject additional attributes', () => {
    expect('![test" onerror="alert(\'xss\')](https://example.com/video.mp4)').toBeParsedAs([
      {type: 'syntax', start: 0, length: 1},
      {type: 'syntax', start: 1, length: 1},
      {type: 'syntax', start: 29, length: 1},
      {type: 'syntax', start: 30, length: 1},
      {type: 'link', start: 31, length: 29},
      {type: 'syntax', start: 60, length: 1},
    ]);
  });

  test('inline code in alt', () => {
    expect('![`code`](https://example.com/video.mp4)').toBeParsedAs([
      {type: 'syntax', start: 0, length: 1},
      {type: 'syntax', start: 1, length: 1},
      {type: 'syntax', start: 8, length: 1},
      {type: 'syntax', start: 9, length: 1},
      {type: 'link', start: 10, length: 29},
      {type: 'syntax', start: 39, length: 1},
    ]);
  });

  test('blockquote in alt', () => {
    expect('![```test```](https://example.com/video.mp4)').toBeParsedAs([
      {type: 'syntax', start: 0, length: 1},
      {type: 'syntax', start: 1, length: 1},
      {type: 'syntax', start: 12, length: 1},
      {type: 'syntax', start: 13, length: 1},
      {type: 'link', start: 14, length: 29},
      {type: 'syntax', start: 43, length: 1},
    ]);
  });
});
```

</details>

Also, there seems to be some problem with parsing ````code````, I believe it should be parsed as a video but currently it's not.

**Comment by nkdengineer** [comment]
@tomekzaw I'll raise follow up PR soon

**Comment by nkdengineer** [comment]
@tomekzaw this is result when i try to parse ````code```` with latest version
Is this expected?

https://github.com/user-attachments/assets/291804df-4ea8-4f89-ad16-a5521ca34b1a

**Comment by tomekzaw** [comment]
@nkdengineer Not sure, but if it works this way (after you send the message), perhaps we should also support it in live-markdown

**Pull request merged**
